### PR TITLE
Modify plugin to emit output with webpack assets

### PR DESCRIPTION
**Pull request by schneidmaster**
Hi --

Thanks a lot for making this plugin -- it's very useful for my Rails + webpack setup.

I've implemented an improvement to how the plugin writes the output file. Instead of using `fs.writeFileSync`, the PR changes the plugin to run at emit time and write the output file to webpack's assets array so it is emitted along with the other assets.

I think this is preferable because it seems like an antipattern using `fs.writeFileSync` in a webpack plugin -- using the webpack API to write the output file avoids unexpected side effects (such as the webpack-dev-server build writing the asset map to disk while serving everything else from memory, which also causes me problems when the webpack output directory doesn't exist in development). It also ensures that the webpack compilation contains a complete manifest of assets (for any code that does something with the compilation -- webpack-dev-server is just one example).

If you think this is a good direction to go, I think it would also make sense to change the plugin API so that the first parameter is an output file name relative to the webpack output path, rather than accepting an absolute path and splitting it as my code currently does. But I thought I'd open a PR first and see what you think.

Cheers,
Zach

Changes:
* Change plugin to run at `emit` instead of `done`
* Add output map to webpack assets array instead of writing directly to filesystem
* Update tests
  * Clear out the `previousChunks` variable between tests -- otherwise it was being cached across tests and causing failures because `assetsEmitted || chunksEmitted` would be false
  * Rewrite the `Only emits if an asset has changed` test -- because the plugin now runs at emit time rather than done time, the assets are emitted a tick later in watch mode. 
* Refactor to improve code style (in second commit)
  * Move `ExtractAssets` and `ExtractChunks` into the plugin class (with pseudo-privacy names) -- seems cleaner and avoids having to pass `this` as a parameter into `ExtractChunks` 
  * Consistently use `const`/`let` instead of `var`

### CODE REVIEW

**Comment by schneidmaster** [comment]
Hey @mtscout6 -- just curious if you have any thoughts on this. Thanks again!

**Comment by mtscout6** [comment]
Sorry for the delay on this, the US holiday threw me off last week. I really like this. Feel free to run with it.

**Comment by mtscout6** [comment]
I moved the repo to an org, and added you to a team in that org with admin permissions over this repo. I also added you as a collaborator on this in npm so you can push the changes to npm when you're ready. Hopefully, that get me out of your way so you can keep doing cool things!

**Comment by schneidmaster** [comment]
Awesome, thanks, I really appreciate it!

**Comment by schneidmaster** [comment]
@mtscout6 Two other quick things:

1) I requested org access for mtscout6-team in Travis -- looks like the CI was disrupted by the repository being moved

2) I [added a LICENSE.txt file](https://github.com/mtscout6-team/asset-map-webpack-plugin/pull/7/commits/6729379579d500f7513ecc88347fafc0142d3db6) -- saw the package was listed as MIT-licensed in the package.json but there was no license file. Just wanted to double-check that's good with you.

**Comment by mtscout6** [comment]
Travis has been approved, and thanks for cleaning up the license that is fine by me.

**Pull request merged**
