### PR TITLE
Concatenates output with resolve

### PR DESCRIPTION
**Pull request by pierreant-p**
In webpack, publicPath can be an url (eg: when you serve your assets
from a CDN.
Using path.join() caused issues, by generating incorrect urls.
Eg:
    path.join('https://my.cdn.com/assets/', 'logo.jpg')
        >> 'https:/my.cdn.com/assets/logo.jpg'  (one / is missing)
    url.resolve('https://my.cdn.com/assets/', 'logo.jpg')
        >> 'https://my.cdn.com/assets/logo.jpg'  (correct)

### CODE REVIEW

**Comment by pierreant-p** [comment]
Before I try and fix the tests, what do you think of the proposal?

**Comment by mtscout6** [comment]
:+1: I like this! I was even considering an option to revisit this since using it on Windows was using `\` instead of `/`.

 Can you add tests for both absolute and relative urls?

**Comment by pierreant-p** [comment]
Hi,

Pull request updated and tests added.
If it's ok for you, I'd love if you could update the package on npm :)

**Comment by mtscout6** [comment]
Published to npm in version 1.2.0 :smile: Thanks!

**Comment by pierreant-p** [comment]
Awesome thanks!

**Pull request merged**
